/// Converting the country code to the country name in Arabic///
/// [countryCode] The two-letter country code
/// Returns the country name in Arabic or null if the symbol is not found
String? convertCodeToCountryName(String countryCode) {
  try {
    return countriesList.firstWhere(
      (Map<String, String> country) => country['code'] == countryCode,
      orElse: () => <String, String>{'name': 'غير معروف'},
    )['name'];
  } catch (e) {
    return null;
  }
}

/// List of countries with their codes and international phone numbers
const List<Map<String, String>> countriesList = <Map<String, String>>[
  <String, String>{'name': 'أفغانستان', 'dial_code': '+93', 'code': 'AF'},
  <String, String>{'name': 'جزر آلاند', 'dial_code': '+358', 'code': 'AX'},
  <String, String>{'name': 'ألبانيا', 'dial_code': '+355', 'code': 'AL'},
  <String, String>{'name': 'الجزائر', 'dial_code': '+213', 'code': 'DZ'},
  <String, String>{'name': 'ساموا الأمريكية', 'dial_code': '+1684', 'code': 'AS'},
  <String, String>{'name': 'أندورا', 'dial_code': '+376', 'code': 'AD'},
  <String, String>{'name': 'أنغولا', 'dial_code': '+244', 'code': 'AO'},
  <String, String>{'name': 'أنغيلا', 'dial_code': '+1264', 'code': 'AI'},
  <String, String>{'name': 'أنتركتيكا', 'dial_code': '+672', 'code': 'AQ'},
  <String, String>{'name': 'أنتيغوا وبربودا', 'dial_code': '+1268', 'code': 'AG'},
  <String, String>{'name': 'الأرجنتين', 'dial_code': '+54', 'code': 'AR'},
  <String, String>{'name': 'أرمينيا', 'dial_code': '+374', 'code': 'AM'},
  <String, String>{'name': 'أروبا', 'dial_code': '+297', 'code': 'AW'},
  <String, String>{'name': 'أستراليا', 'dial_code': '+61', 'code': 'AU'},
  <String, String>{'name': 'النمسا', 'dial_code': '+43', 'code': 'AT'},
  <String, String>{'name': 'أذربيجان', 'dial_code': '+994', 'code': 'AZ'},
  <String, String>{'name': 'جزر البهاما', 'dial_code': '+1242', 'code': 'BS'},
  <String, String>{'name': 'البحرين', 'dial_code': '+973', 'code': 'BH'},
  <String, String>{'name': 'بنغلاديش', 'dial_code': '+880', 'code': 'BD'},
  <String, String>{'name': 'بربادوس', 'dial_code': '+1246', 'code': 'BB'},
  <String, String>{'name': 'بيلاروسيا', 'dial_code': '+375', 'code': 'BY'},
  <String, String>{'name': 'بلجيكا', 'dial_code': '+32', 'code': 'BE'},
  <String, String>{'name': 'بليز', 'dial_code': '+501', 'code': 'BZ'},
  <String, String>{'name': 'بنين', 'dial_code': '+229', 'code': 'BJ'},
  <String, String>{'name': 'برمودا', 'dial_code': '+1441', 'code': 'BM'},
  <String, String>{'name': 'بوتان', 'dial_code': '+975', 'code': 'BT'},
  <String, String>{'name': 'بوليفيا', 'dial_code': '+591', 'code': 'BO'},
  <String, String>{'name': 'البوسنة والهرسك', 'dial_code': '+387', 'code': 'BA'},
  <String, String>{'name': 'بوتسوانا', 'dial_code': '+267', 'code': 'BW'},
  <String, String>{'name': 'البرازيل', 'dial_code': '+55', 'code': 'BR'},
  <String, String>{'name': 'إقليم المحيط البريطاني الهندي', 'dial_code': '+246', 'code': 'IO'},
  <String, String>{'name': 'بروناي دار السلام', 'dial_code': '+673', 'code': 'BN'},
  <String, String>{'name': 'بلغاريا', 'dial_code': '+359', 'code': 'BG'},
  <String, String>{'name': 'بوركينا فاسو', 'dial_code': '+226', 'code': 'BF'},
  <String, String>{'name': 'بوروندي', 'dial_code': '+257', 'code': 'BI'},
  <String, String>{'name': 'كمبوديا', 'dial_code': '+855', 'code': 'KH'},
  <String, String>{'name': 'الكاميرون', 'dial_code': '+237', 'code': 'CM'},
  <String, String>{'name': 'كندا', 'dial_code': '+1', 'code': 'CA'},
  <String, String>{'name': 'الرأس الأخضر', 'dial_code': '+238', 'code': 'CV'},
  <String, String>{'name': 'جزر كايمان', 'dial_code': '+ 345', 'code': 'KY'},
  <String, String>{'name': 'جمهورية افريقيا الوسطى', 'dial_code': '+236', 'code': 'CF'},
  <String, String>{'name': 'تشاد', 'dial_code': '+235', 'code': 'TD'},
  <String, String>{'name': 'تشيلي', 'dial_code': '+56', 'code': 'CL'},
  <String, String>{'name': 'الصين', 'dial_code': '+86', 'code': 'CN'},
  <String, String>{'name': 'جزيرة الكريسماس', 'dial_code': '+61', 'code': 'CX'},
  <String, String>{'name': 'جزر كوكوس (كيلينغ)', 'dial_code': '+61', 'code': 'CC'},
  <String, String>{'name': 'كولومبيا', 'dial_code': '+57', 'code': 'CO'},
  <String, String>{'name': 'جزر القمر', 'dial_code': '+269', 'code': 'KM'},
  <String, String>{'name': 'الكونغو', 'dial_code': '+242', 'code': 'CG'},
  <String, String>{'name': 'الكونغو الديمقراطية', 'dial_code': '+243', 'code': 'CD'},
  <String, String>{'name': 'جزر كوك', 'dial_code': '+682', 'code': 'CK'},
  <String, String>{'name': 'كوستا ريكا', 'dial_code': '+506', 'code': 'CR'},
  <String, String>{'name': 'ساحل العاج', 'dial_code': '+225', 'code': 'CI'},
  <String, String>{'name': 'كرواتيا', 'dial_code': '+385', 'code': 'HR'},
  <String, String>{'name': 'كوبا', 'dial_code': '+53', 'code': 'CU'},
  <String, String>{'name': 'قبرص', 'dial_code': '+357', 'code': 'CY'},
  <String, String>{'name': 'الجمهورية التشيكية', 'dial_code': '+420', 'code': 'CZ'},
  <String, String>{'name': 'الدنمارك', 'dial_code': '+45', 'code': 'DK'},
  <String, String>{'name': 'جيبوتي', 'dial_code': '+253', 'code': 'DJ'},
  <String, String>{'name': 'دومينيكا', 'dial_code': '+1767', 'code': 'DM'},
  <String, String>{'name': 'جمهورية الدومينيكان', 'dial_code': '+1849', 'code': 'DO'},
  <String, String>{'name': 'الاكوادور', 'dial_code': '+593', 'code': 'EC'},
  <String, String>{'name': 'مصر', 'dial_code': '+20', 'code': 'EG'},
  <String, String>{'name': 'سلفادور', 'dial_code': '+503', 'code': 'SV'},
  <String, String>{'name': 'غينيا الإستوائية', 'dial_code': '+240', 'code': 'GQ'},
  <String, String>{'name': 'إريتريا', 'dial_code': '+291', 'code': 'ER'},
  <String, String>{'name': 'إستونيا', 'dial_code': '+372', 'code': 'EE'},
  <String, String>{'name': 'أثيوبيا', 'dial_code': '+251', 'code': 'ET'},
  <String, String>{'name': 'جزر فوكلاند (مالفيناس)', 'dial_code': '+500', 'code': 'FK'},
  <String, String>{'name': 'جزر فاروس', 'dial_code': '+298', 'code': 'FO'},
  <String, String>{'name': 'فيجي', 'dial_code': '+679', 'code': 'FJ'},
  <String, String>{'name': 'فنلندا', 'dial_code': '+358', 'code': 'FI'},
  <String, String>{'name': 'فرنسا', 'dial_code': '+33', 'code': 'FR'},
  <String, String>{'name': 'غيانا الفرنسية', 'dial_code': '+594', 'code': 'GF'},
  <String, String>{'name': 'بولينيزيا الفرنسية', 'dial_code': '+689', 'code': 'PF'},
  <String, String>{'name': 'الجابون', 'dial_code': '+241', 'code': 'GA'},
  <String, String>{'name': 'غامبيا', 'dial_code': '+220', 'code': 'GM'},
  <String, String>{'name': 'جورجيا', 'dial_code': '+995', 'code': 'GE'},
  <String, String>{'name': 'ألمانيا', 'dial_code': '+49', 'code': 'DE'},
  <String, String>{'name': 'غانا', 'dial_code': '+233', 'code': 'GH'},
  <String, String>{'name': 'جبل طارق', 'dial_code': '+350', 'code': 'GI'},
  <String, String>{'name': 'اليونان', 'dial_code': '+30', 'code': 'GR'},
  <String, String>{'name': 'الأرض الخضراء', 'dial_code': '+299', 'code': 'GL'},
  <String, String>{'name': 'غرينادا', 'dial_code': '+1473', 'code': 'GD'},
  <String, String>{'name': 'جوادلوب', 'dial_code': '+590', 'code': 'GP'},
  <String, String>{'name': 'غوام', 'dial_code': '+1671', 'code': 'GU'},
  <String, String>{'name': 'غواتيمالا', 'dial_code': '+502', 'code': 'GT'},
  <String, String>{'name': 'غيرنسي', 'dial_code': '+44', 'code': 'GG'},
  <String, String>{'name': 'غينيا', 'dial_code': '+224', 'code': 'GN'},
  <String, String>{'name': 'غينيا بيساو', 'dial_code': '+245', 'code': 'GW'},
  <String, String>{'name': 'غيانا', 'dial_code': '+595', 'code': 'GY'},
  <String, String>{'name': 'هايتي', 'dial_code': '+509', 'code': 'HT'},
  <String, String>{'name': 'الفاتيكان', 'dial_code': '+379', 'code': 'VA'},
  <String, String>{'name': 'هندوراس', 'dial_code': '+504', 'code': 'HN'},
  <String, String>{'name': 'هونج كونج', 'dial_code': '+852', 'code': 'HK'},
  <String, String>{'name': 'هنغاريا', 'dial_code': '+36', 'code': 'HU'},
  <String, String>{'name': 'أيسلندا', 'dial_code': '+354', 'code': 'IS'},
  <String, String>{'name': 'الهند', 'dial_code': '+91', 'code': 'IN'},
  <String, String>{'name': 'إندونيسيا', 'dial_code': '+62', 'code': 'ID'},
  <String, String>{'name': 'إيران', 'dial_code': '+98', 'code': 'IR'},
  <String, String>{'name': 'العراق', 'dial_code': '+964', 'code': 'IQ'},
  <String, String>{'name': 'أيرلندا', 'dial_code': '+353', 'code': 'IE'},
  <String, String>{'name': 'جزيرة آيل أوف مان', 'dial_code': '+44', 'code': 'IM'},
  <String, String>{'name': 'ارض فلسطين المحتلة', 'dial_code': '+972', 'code': 'IL'},
  <String, String>{'name': 'إيطاليا', 'dial_code': '+39', 'code': 'IT'},
  <String, String>{'name': 'جامايكا', 'dial_code': '+1876', 'code': 'JM'},
  <String, String>{'name': 'اليابان', 'dial_code': '+81', 'code': 'JP'},
  <String, String>{'name': 'جيرسي', 'dial_code': '+44', 'code': 'JE'},
  <String, String>{'name': 'الأردن', 'dial_code': '+962', 'code': 'JO'},
  <String, String>{'name': 'كازاخستان', 'dial_code': '+77', 'code': 'KZ'},
  <String, String>{'name': 'كينيا', 'dial_code': '+254', 'code': 'KE'},
  <String, String>{'name': 'كيريباتي', 'dial_code': '+686', 'code': 'KI'},
  <String, String>{'name': 'كوريا الشمالية', 'dial_code': '+850', 'code': 'KP'},
  <String, String>{'name': 'كورياالجنوبية', 'dial_code': '+82', 'code': 'KR'},
  <String, String>{'name': 'الكويت', 'dial_code': '+965', 'code': 'KW'},
  <String, String>{'name': 'قيرغيزستان', 'dial_code': '+996', 'code': 'KG'},
  <String, String>{'name': 'لاوس', 'dial_code': '+856', 'code': 'LA'},
  <String, String>{'name': 'لاتفيا', 'dial_code': '+371', 'code': 'LV'},
  <String, String>{'name': 'لبنان', 'dial_code': '+961', 'code': 'LB'},
  <String, String>{'name': 'ليسوتو', 'dial_code': '+266', 'code': 'LS'},
  <String, String>{'name': 'ليبيريا', 'dial_code': '+231', 'code': 'LR'},
  <String, String>{'name': 'ليبيا', 'dial_code': '+218', 'code': 'LY'},
  <String, String>{'name': 'ليختنشتاين', 'dial_code': '+423', 'code': 'LI'},
  <String, String>{'name': 'ليتوانيا', 'dial_code': '+370', 'code': 'LT'},
  <String, String>{'name': 'لوكسمبورغ', 'dial_code': '+352', 'code': 'LU'},
  <String, String>{'name': 'ماكاو', 'dial_code': '+853', 'code': 'MO'},
  <String, String>{'name': 'مقدونيا', 'dial_code': '+389', 'code': 'MK'},
  <String, String>{'name': 'مدغشقر', 'dial_code': '+261', 'code': 'MG'},
  <String, String>{'name': 'ملاوي', 'dial_code': '+265', 'code': 'MW'},
  <String, String>{'name': 'ماليزيا', 'dial_code': '+60', 'code': 'MY'},
  <String, String>{'name': 'جزر المالديف', 'dial_code': '+960', 'code': 'MV'},
  <String, String>{'name': 'مالي', 'dial_code': '+223', 'code': 'ML'},
  <String, String>{'name': 'مالطا', 'dial_code': '+356', 'code': 'MT'},
  <String, String>{'name': 'جزر مارشال', 'dial_code': '+692', 'code': 'MH'},
  <String, String>{'name': 'مارتينيك', 'dial_code': '+596', 'code': 'MQ'},
  <String, String>{'name': 'موريتانيا', 'dial_code': '+222', 'code': 'MR'},
  <String, String>{'name': 'موريشيوس', 'dial_code': '+230', 'code': 'MU'},
  <String, String>{'name': 'ضائع', 'dial_code': '+262', 'code': 'YT'},
  <String, String>{'name': 'المكسيك', 'dial_code': '+52', 'code': 'MX'},
  <String, String>{'name': 'ولايات ميكرونيزيا الموحدة', 'dial_code': '+691', 'code': 'FM'},
  <String, String>{'name': 'مولدوفا', 'dial_code': '+373', 'code': 'MD'},
  <String, String>{'name': 'موناكو', 'dial_code': '+377', 'code': 'MC'},
  <String, String>{'name': 'منغوليا', 'dial_code': '+976', 'code': 'MN'},
  <String, String>{'name': 'الجبل الأسود', 'dial_code': '+382', 'code': 'ME'},
  <String, String>{'name': 'مونتسيرات', 'dial_code': '+1664', 'code': 'MS'},
  <String, String>{'name': 'المغرب', 'dial_code': '+212', 'code': 'MA'},
  <String, String>{'name': 'موزمبيق', 'dial_code': '+258', 'code': 'MZ'},
  <String, String>{'name': 'ميانمار', 'dial_code': '+95', 'code': 'MM'},
  <String, String>{'name': 'ناميبيا', 'dial_code': '+264', 'code': 'NA'},
  <String, String>{'name': 'ناورو', 'dial_code': '+674', 'code': 'NR'},
  <String, String>{'name': 'نيبال', 'dial_code': '+977', 'code': 'NP'},
  <String, String>{'name': 'هولندا', 'dial_code': '+31', 'code': 'NL'},
  <String, String>{'name': 'جزر الأنتيل الهولندية', 'dial_code': '+599', 'code': 'AN'},
  <String, String>{'name': 'كاليدونيا الجديدة', 'dial_code': '+687', 'code': 'NC'},
  <String, String>{'name': 'نيوزيلاندا', 'dial_code': '+64', 'code': 'NZ'},
  <String, String>{'name': 'نيكاراغوا', 'dial_code': '+505', 'code': 'NI'},
  <String, String>{'name': 'النيجر', 'dial_code': '+227', 'code': 'NE'},
  <String, String>{'name': 'نيجيريا', 'dial_code': '+234', 'code': 'NG'},
  <String, String>{'name': 'نيوي', 'dial_code': '+683', 'code': 'NU'},
  <String, String>{'name': 'جزيرة نورفولك', 'dial_code': '+672', 'code': 'NF'},
  <String, String>{'name': 'جزر مريانا الشمالية', 'dial_code': '+1670', 'code': 'MP'},
  <String, String>{'name': 'النرويج', 'dial_code': '+47', 'code': 'NO'},
  <String, String>{'name': 'سلطنة عمان', 'dial_code': '+968', 'code': 'OM'},
  <String, String>{'name': 'باكستان', 'dial_code': '+92', 'code': 'PK'},
  <String, String>{'name': 'بالاو', 'dial_code': '+680', 'code': 'PW'},
  <String, String>{'name': 'الأراضي الفلسطينية المحتلة', 'dial_code': '+970', 'code': 'PS'},
  <String, String>{'name': 'بنما', 'dial_code': '+507', 'code': 'PA'},
  <String, String>{'name': 'بابوا غينيا الجديدة', 'dial_code': '+675', 'code': 'PG'},
  <String, String>{'name': 'باراغواي', 'dial_code': '+595', 'code': 'PY'},
  <String, String>{'name': 'بيرو', 'dial_code': '+51', 'code': 'PE'},
  <String, String>{'name': 'الفيلبين', 'dial_code': '+63', 'code': 'PH'},
  <String, String>{'name': 'بيتكيرن', 'dial_code': '+872', 'code': 'PN'},
  <String, String>{'name': 'بولندا', 'dial_code': '+48', 'code': 'PL'},
  <String, String>{'name': 'البرتغال', 'dial_code': '+351', 'code': 'PT'},
  <String, String>{'name': 'بورتوريكو', 'dial_code': '+1939', 'code': 'PR'},
  <String, String>{'name': 'دولة قطر', 'dial_code': '+974', 'code': 'QA'},
  <String, String>{'name': 'رومانيا', 'dial_code': '+40', 'code': 'RO'},
  <String, String>{'name': 'روسيا', 'dial_code': '+7', 'code': 'RU'},
  <String, String>{'name': 'رواندا', 'dial_code': '+250', 'code': 'RW'},
  <String, String>{'name': 'Reunion', 'dial_code': '+262', 'code': 'RE'},
  <String, String>{'name': 'سانت بارتيليمي', 'dial_code': '+590', 'code': 'BL'},
  <String, String>{'name': 'سانت هيلانة وأسنسيون وتريستان دا كونها', 'dial_code': '+290', 'code': 'SH'},
  <String, String>{'name': 'سانت كيتس ونيفيس', 'dial_code': '+1869', 'code': 'KN'},
  <String, String>{'name': 'سانت لوسيا', 'dial_code': '+1758', 'code': 'LC'},
  <String, String>{'name': 'سانت مارتن', 'dial_code': '+590', 'code': 'MF'},
  <String, String>{'name': 'سانت بيير وميكلون', 'dial_code': '+508', 'code': 'PM'},
  <String, String>{'name': 'سانت فنسنت وجزر غرينادين', 'dial_code': '+1784', 'code': 'VC'},
  <String, String>{'name': 'ساموا', 'dial_code': '+685', 'code': 'WS'},
  <String, String>{'name': 'سان مارينو', 'dial_code': '+378', 'code': 'SM'},
  <String, String>{'name': 'ساو تومي وبرينسيبي', 'dial_code': '+239', 'code': 'ST'},
  <String, String>{'name': 'المملكة العربية السعودية', 'dial_code': '+966', 'code': 'SA'},
  <String, String>{'name': 'السنغال', 'dial_code': '+221', 'code': 'SN'},
  <String, String>{'name': 'صربيا', 'dial_code': '+381', 'code': 'RS'},
  <String, String>{'name': 'سيشيل', 'dial_code': '+248', 'code': 'SC'},
  <String, String>{'name': 'سيرا ليون', 'dial_code': '+232', 'code': 'SL'},
  <String, String>{'name': 'سنغافورة', 'dial_code': '+65', 'code': 'SG'},
  <String, String>{'name': 'سلوفاكيا', 'dial_code': '+421', 'code': 'SK'},
  <String, String>{'name': 'سلوفينيا', 'dial_code': '+386', 'code': 'SI'},
  <String, String>{'name': 'جزر سليمان', 'dial_code': '+677', 'code': 'SB'},
  <String, String>{'name': 'الصومال', 'dial_code': '+252', 'code': 'SO'},
  <String, String>{'name': 'جنوب أفريقيا', 'dial_code': '+27', 'code': 'ZA'},
  <String, String>{'name': 'جنوب السودان', 'dial_code': '+211', 'code': 'SS'},
  <String, String>{'name': 'جورجيا الجنوبية وجزر ساندويتش الجنوبية', 'dial_code': '+500', 'code': 'GS'},
  <String, String>{'name': 'إسبانيا', 'dial_code': '+34', 'code': 'ES'},
  <String, String>{'name': 'سيريلانكا', 'dial_code': '+94', 'code': 'LK'},
  <String, String>{'name': 'السودان', 'dial_code': '+249', 'code': 'SD'},
  <String, String>{'name': 'سورينام', 'dial_code': '+597', 'code': 'SR'},
  <String, String>{'name': 'سفالبارد وجان ماين', 'dial_code': '+47', 'code': 'SJ'},
  <String, String>{'name': 'سوازيلاند', 'dial_code': '+268', 'code': 'SZ'},
  <String, String>{'name': 'السويد', 'dial_code': '+46', 'code': 'SE'},
  <String, String>{'name': 'سويسرا', 'dial_code': '+41', 'code': 'CH'},
  <String, String>{'name': 'الجمهورية العربية السورية', 'dial_code': '+963', 'code': 'SY'},
  <String, String>{'name': 'تايوان', 'dial_code': '+886', 'code': 'TW'},
  <String, String>{'name': 'طاجيكستان', 'dial_code': '+992', 'code': 'TJ'},
  <String, String>{'name': 'تنزانيا', 'dial_code': '+255', 'code': 'TZ'},
  <String, String>{'name': 'تايلاند', 'dial_code': '+66', 'code': 'TH'},
  <String, String>{'name': 'تيمور ليشتي', 'dial_code': '+670', 'code': 'TL'},
  <String, String>{'name': 'توجو', 'dial_code': '+228', 'code': 'TG'},
  <String, String>{'name': 'توكيلاو', 'dial_code': '+690', 'code': 'TK'},
  <String, String>{'name': 'تونغا', 'dial_code': '+676', 'code': 'TO'},
  <String, String>{'name': 'ترينداد وتوباغو', 'dial_code': '+1868', 'code': 'TT'},
  <String, String>{'name': 'تونس', 'dial_code': '+216', 'code': 'TN'},
  <String, String>{'name': 'تركيا', 'dial_code': '+90', 'code': 'TR'},
  <String, String>{'name': 'تركمانستان', 'dial_code': '+993', 'code': 'TM'},
  <String, String>{'name': 'جزر تركس وكايكوس', 'dial_code': '+1649', 'code': 'TC'},
  <String, String>{'name': 'توفالو', 'dial_code': '+688', 'code': 'TV'},
  <String, String>{'name': 'أوغندا', 'dial_code': '+256', 'code': 'UG'},
  <String, String>{'name': 'أوكرانيا', 'dial_code': '+380', 'code': 'UA'},
  <String, String>{'name': 'الإمارات العربية المتحدة', 'dial_code': '+971', 'code': 'AE'},
  <String, String>{'name': 'المملكة المتحدة', 'dial_code': '+44', 'code': 'GB'},
  <String, String>{'name': 'الولايات المتحدة الأمريكية', 'dial_code': '+1', 'code': 'US'},
  <String, String>{'name': 'أوروغواي', 'dial_code': '+598', 'code': 'UY'},
  <String, String>{'name': 'أوزبكستان', 'dial_code': '+998', 'code': 'UZ'},
  <String, String>{'name': 'فانواتو', 'dial_code': '+678', 'code': 'VU'},
  <String, String>{'name': 'Venezuela, Bolivarian Republic of Venezuela', 'dial_code': '+58', 'code': 'VE'},
  <String, String>{'name': 'Vietnam', 'dial_code': '+84', 'code': 'VN'},
  <String, String>{'name': 'Virgin Islands, British', 'dial_code': '+1284', 'code': 'VG'},
  <String, String>{'name': 'Virgin Islands, U.S.', 'dial_code': '+1340', 'code': 'VI'},
  <String, String>{'name': 'Wallis and Futuna', 'dial_code': '+681', 'code': 'WF'},
  <String, String>{'name': 'Yemen', 'dial_code': '+967', 'code': 'YE'},
  <String, String>{'name': 'Zambia', 'dial_code': '+260', 'code': 'ZM'},
  <String, String>{'name': 'Zimbabwe', 'dial_code': '+263', 'code': 'ZW'}
];
