// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgtv4VcKHkgEk_hipWzypvvQrm7pN_JcU',
    appId: '1:992194948893:android:99e5c1d025f1363f15fbf4',
    messagingSenderId: '992194948893',
    projectId: 'rasid-1e3da',
    storageBucket: 'rasid-1e3da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLbn43-uzbcSOOgyFK1zyt2-ir3xhiFAQ',
    appId: '1:992194948893:ios:ae12b91268b072a115fbf4',
    messagingSenderId: '992194948893',
    projectId: 'rasid-1e3da',
    storageBucket: 'rasid-1e3da.appspot.com',
    androidClientId:
        '992194948893-1q94mfn6vtn6bmm0l5n9dea6k4b9cjc3.apps.googleusercontent.com',
    iosClientId:
        '992194948893-gdojll9egj247s3cf6fi25evstadmnu3.apps.googleusercontent.com',
    iosBundleId: 'com.rassid',
  );
}
